server:
  port: 8082

mensaje: "hola desde microservicio 2"

resilience4j:
  circuitbreaker:
    instances:
      productServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      productServiceRetry:
        maxAttempts: 3
        waitDuration: 1s
  timelimiter:
    instances:
      productServiceTimeLimiter:
        timeoutDuration: 2s
