server:
  port: 8091
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tarea-service
    username: cibertec
    password: P3rdigon@159
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      platform: org.hibernate.dialect.MySQLDialect

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
    secret: a1B!c2D@e3F#g4H$i5J%k6LF#g4H$i5J%k6L^m7N&o8P*q9R
