server:
    port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tt_userservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cibertec
    password: P3rdigon@159
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
    secret: a1B!c2D@e3F#g4H$i5J%k6LF#g4H$i5J%k6L^m7N&o8P*q9R
    expirationMs: 36000000
